var mistype1 = {"2": ["Appeals to principles over personal feelings.", "Defend autonomy.", "Restrained in expression of positive feelings, but easier to express negative feelings."],
                "3": ["Idealists, striving for perfection. Efficient for the sake of reaching the desired standard.", "Attached to methods or procedures.", "Less able to conceal irritations and disappointments.", "Able to suppress feelings for the time being.", "“Listen to me—I know the right way to do things.” Offers themselves as examples of high standard."],
                "4": ["Attend to responsibilities first, feelings later. Would not allow self to “indulge” in feelings very long.", "Critical over others’ inefficiency or failures.", "Respond by pushing other party harder.", "This type, when stressed, looks like an unhealthy Type B—moody and irrational."],
                "5": ["More from the gut. Emphasis on certainty and judgment.", "More interested in using thoughts to relate more perfectly to themselves and the world.", "Judge from idealistic standards."],
                "6": ["Self-controlled, impersonal efficiency, orderliness, propriety.", "Compliant to demands of ideals.", "'Inner Critic' in the head.", "Guilty when doing something contrary to ideals."],
                "7": ["This type, when growing, looks like a healthy Type A—spontaneous and joyful.", "Hold high standards and expect to be disappointed.", "Know their mission.", "True perfectionism drives them to be angry and critique themselves.", "Rigid in plans, often focused. Quite self-conscious socially. Driven by anger."],
                "8": ["This type tries to convince others to do the right thing from a moral standpoint.", "View justice as an extremely important value to restore humans to a certain standard.", "This type is more compliant to their ideals."],
                "9": ["When facing conflict, the principle is foremost and will drive home their point, even if it causes arguments.", "More driven, having difficulty taking a break.", "When handling stress, at first try harder, but then may end up being moody."],
                };

var mistype2 = {"1": ["Highly personal.", "Seek close connection.", "Unrestrained in positive feelings, but more difficult to express negative feelings."],
                "3": ["This type attempts to get others to like them by doing good things for them, focusing on the other person.", "Openly sentimental and emote easily.", "Overexert themselves and lose patience, blowing up.", "Feel uncomfortable going after goals directly, feeling it would be too selfish."],
                "4": ["This type tends to move toward others and engage them.", "Looks for people to rescue.", "Aware of others’ feelings, but unaware of own needs."],
                "5": ["This type is emotionally expressive and highly people-oriented.", "Copes by winning people over.", "Go by feelings."],
                "6": ["This type wants to be loved and be important to others.", "Try to win favor by operating out of warmth and friendliness, offering their love and friendship.", "“Throw out net of feelings” to see whom they can sweep into their lives.", "Want to be close with others.", "Openly warm and demonstrative about how they feel toward others."],
                "7": ["Deeply feeling, with emotions changing less.", "More interpersonal, genuinely friendly, warm, and interested in others.", "Desire to be important.", "Want others to need them.", "Possessive of their friends due to high investment.", "Like to indulge in sharing feelings and intimacies."],
                "8": ["Do so indirectly, often disguised as concern for others.", "Difficulty communicating anger, even though they may be very upset with someone, resorting to indirect approaches.", "This type tends to handle conflict with covert neediness and manipulation.", "This type, when stressed, looks like an unhealthy Type B—aggressive and dominating."],
                "9": ["The way this type loves is by understanding what needs to be met, and trying to meet them in order to get closer and to be relied on.", "Sharp sense of own identity.", "When stressed, become more self-important and aggressive.", "Goes the extra mile for you."],
                };

var mistype3 = {"1": ["Pragmatic, driven by goals. Efficient for the sake of just getting it done.", "More adaptable to get desired result.", "More able to mask what is bothering them.", "Detachment of feelings.", "“Be like me—I have got it together. Offers themselves as exemplars of individual perfection."],
                "2": ["This type attempts to get others to like them by developing excellence, thus gaining attention.", "More composed and have difficulty accessing feelings.", "Overexert themselves and burn out, becoming detached and passive.", "Are very goal-driven."],
                "4": ["Tend to focus on task, on efficiency, on performance, pushing aside feelings.", "Might be seen from the other type as inauthentic."],
                "5": ["Very goal-oriented.", "Changes interests and careers rapidly to seek success.", "Tend to promote themselves.", "Highly sociable."],
                "6": ["See themselves as soloists, wanting to excel to be the best they can be.", "Tend to be smooth and composed."],
                "7": ["This type desires to reinforce their feeling of superiority and hence sense of self.", "This type does so in order to create exclusivity for being of the “in crowd.”", "Desires to rise above other competitively.", "This type has an inflated sense of self-worth.", "Cool, in control, projecting the impression that they are perfectly together, with no emotional or personal problems."],
                "8": ["This type spends a lot of time comparing themselves to others.", "Are natural managers and technicians.", "Fear failure because of personal humiliation.", "Focus on others’ opinions in conjunction with achievements."],
                "9": ["This type, when stressed, looks like an unhealthy Type B—disengaged and apathetic.", "Highly motivated self-starters.", "Try to garner attention from people who believe are important to them.", "Get excited about projects."],
                };

var mistype4 = {"1": ["Want to sort out feelings first, deal with duties after. Might not be able to mobilize self to meet responsibilities.", "Critical over others’ lack of awareness of sensitivities.", "Respond by withdrawing.", "This type, when growing, looks like a healthy Type A—more objective and principled."],
                "2": ["This type tends to withdraw from others, hoping that others will seek them out.", "Looks for someone to rescue them.", "Highly aware of own emotional state, but may not recognize impact on others."],
                "3": ["Want to accomplish things too, but when difficult feelings arise, they want to stop and process before returning to tasks.", "Might be seen from the other type as unprofessional."],
                "5": ["This type is more self-absorbed and emotionally volatile, expressing emotions and expecting responses in certain ways.", "Tend to focus on disappointments in love and with childhood."],
                "6": ["This type becomes depressed because of personal disappointment for having lost opportunity to actualize themselves.", "Tend to be original creators.", "Relate primarily to own inner emotional state.", "True introverts."],
                "7": ["Excessive and indulgent with emotional extremes.", "Cherishing things for the sake of beauty."],
                "8": ["This type finds it difficult to let go of wounds and “getting over it.”", "This type shows vulnerability, but in reality are rather strong inside."],
                "9": ["The artistry of this type is more personal and self-revealing.", "Often deals with the tragic.", "Withdraw from others to protect themselves and give time to process emotions.", "Detached from whatever caused them pain.", "Not comforted by seeing others living a happier, more normal life."],
                };

var mistype5 = {"1": ["More from the mind. Relative lack of certainty and difficulty with discernment.", "More interested in how ideas relate to other thoughts that arise in the mind.", "Constantly investigating and questioning assumptions."],
                "2": ["This type is emotionally detached and can be known as loners.", "Copes by detaching from hurt and isolating self.", "Go by intellectual concepts."],
                "3": ["Very process-oriented, not caring much about the final goal.", "Follow their ideas wherever it takes them.", "Tend to be secretive.", "Usually loners."],
                "4": ["This type might have intense feelings but share them with few people, fueling thoughts and imagination.", "Tend to focus on inner emptiness and feelings of meaningless."],
                "6": ["Tend to be more non-linear. They are interested in finding out where theories break down and develop original ideas.", "Feel can mostly only trust their minds to come to conclusions."],
                "7": ["This type tends to be more socially isolated and withdrawn.", "Their gift is intense focus and concentration.", "Focus more on the nihilistic, realistic side of things.", "This type, when stressed, looks like an unhealthy Type B—hyperactive and scattered."],
                "8": ["This type tends to stay in their heads more, having more difficulty being grounded and practical.", "This type, when growing, looks like  healthy Type B—self-confident and decisive."],
                "9": ["This type is more strong-minded and resistant to the influence of others.", "More suspicious of people.", "More involved with details.", "Tend to speculate on problems.", "Attempts to see if their ideas might come true.", "Often get lost in complex interpretations of reality.", "Are afraid of being overwhelmed by the world and use thinking as a defense against it."],
                };

var mistype6 = {"1": ["Anxious, indecisive, ambivalent, reactive.", "Compliant to demands of other people.", "“Inner Committee” in the head.", "Guilty when doing something contrary to the commitments to allies, beliefs, and authorities."],
                "2": ["This type wants to have the approval and support of others.", "Try to win favor by being playful and silly to elicit emotional response.", "Warily invite selected people into their lives.", "Want to create partnerships with others that will support them—but not too close.", "Ambivalent about feelings, often anxious."],
                "3": ["Tend to feel awkward about taking the spotlight.", "Tend to be (often endearingly) more nervous and awkward."],
                "4": ["This type becomes depressed when fearing they have done something to make an authority figure mad at them.", "Tend to be performing artists.", "Usually relate well to people.", "More ambiverted."],
                "5": ["Tend to be more linear and analytical because more interested in troubleshooting and predictions.", "Do not really trust their own minds to come to meaningful conclusions."],
                "7": ["This type tends to react to anxiety by fretting and becoming more anxious.", "Persistent sense of commitment, having a higher sense of responsibility and working to meet all obligations first."],
                "8": ["This type becomes aggressive because they do not want to be pushed around anymore (more defensive).", "Eventually may yield if enough pressure applied to them."],
                "9": ["Have a more difficult time disguising feelings.", "Tend to be suspicious of unknown people and situations.", "This type, when growing, looks like  healthy Type B—relaxed and optimistic."],
                };

var mistype7 = {"1": ["This type, when stressed, looks like an unhealthy Type A—perfectionistic and critical.", "Usually very optimistic about the future.", "“Feel” their mission.", "“Perfectionism” drives them to become frustrated because of failed expectations (the optimistic outcome did not occur).", "Spontaneous in plans, sometimes scattered. Unselfconscious socially. Driven by anxiety."],
                "2": ["Quicker, more fickle emotions.", "Do not get as involved in people’s lives, but like to float around people to bring more enjoyment.", "Desire to have a good time with people around.", "Do not want to be needed by others—have little patience for anyone who is too dependent on them.", "Tend to be less attached to people, not as clingy.", "Like to indulge in filling minds with interesting possibilities and concepts."],
                "3": ["This type desires to possess things and hence sense of self.", "This type does so to experience whatever is new and exciting right away.", "Desires continuous stream of environmental stimulation.", "This type has an inflated appetite.", "Have many more rough edges, rarely seeming as perfect or as coolly self-contained as Type A."],
                "4": ["Excessive and indulgent with possessions and experiences.", "Cherishing things for the sake of stimulation."],
                "5": ["This type is highly gregarious.", "Their gift is breadth of vision and synthesis.", "Focus more on the positive side of things.", "This type, when growing, looks like a healthy Type A—focused and fascinated by life."],
                "6": ["This type tends to react to anxiety by looking for enjoyable distractions.", "Much more spontaneous, resistant to having too many expectations placed on them."],
                "8": ["This type is primarily interested in variety.", "See themselves as idealistic optimists, often getting ahead of themselves."],
                "9": ["This type tends to avoid conflict or over excitement.", "As they become unhealthier, become more passive and indifferent.", "Seeks to maintain state of contentment--not too excited nor in discomfort."],
                };

var mistype8 = {"1": ["This type tries to convince using personal convictions and own self-confidence.", "View justice with more of a visceral response, rushing in to protect others.", "This type is more given over to their gut response."],
                "2": ["Do so directly, making it clear that there is a power struggle.", "Openly aggressive, very direct in communication.", "This type tends to handle conflict with intense passion in interpersonal conflicts.", "This type, when growing, looks like a healthy Type A—open-hearted and caring."],
                "3": ["This type is self-assertive and want others to give way as not to waste energy.", "Are leaders who want to make the world conform to their personal vision.", "See failure as an opportunity to learn and come back stronger.", "Focus on achieving purposes rather than others’ opinions."],
                "4": ["This type tries to toughen up and “get over it” in order to maintain independence and personal authority.", "This type shows strength, but in reality are rather vulnerable inside."],
                "5": ["This type is more instinctual and are of practical action.", "This type, when stressed, looks like an unhealthy Type B—secretive and fearful."],
                "6": ["This type becomes aggressive to achieve what they want (more offensive).", "More pressure encourages them to remain defiant."],
                "7": ["This type is primarily interested in intensity.", "See themselves as hard-nosed realists, generally remaining grounded and down to earth."],
                "9": ["Much more openly assertive and do not mind engaging in conflicts to make a point.", "As they become unhealthier, become angrier and more aggressive."],
                };

var mistype9 = {"1": ["When facing conflict, even if this type may hold strong personal convictions, they generally do not want to start arguments.", "Enjoy down time, easily able to take a break.", "When handling stress, become disengaged and resistant, but then may end up being anxious and reactive."],
                "2": ["The way this type loves is by supporting others emotionally without looking for much in return.", "Self-effacing and accommodating.", "When stressed, become more self-effacing and withdrawn.", "Wishes you well and offers reassurance."],
                "3": ["This type, when growing, looks like a healthy Type A—self-developing and energetic.", "Often kept motivated and on track through accountability.", "Trouble doing good things for themselves.", "Get excited about free time and comforts."],
                "4": ["The artistry of this type often expresses idealization.", "Often deals in the commonplace.", "Withdraw from others to remove attention from circumstances that threaten them.", "Detached both from external world and emotions.", "Comforted by seeing the world through rose-colored glasses."],
                "5": ["This type is more patient and accommodating.", "Much more trusting of people.", "More involved with generalities.", "Tend to focus on identifying solutions to problems.", "Tend to ruminate on their fantasies.", "Often simplify and reinterpret reality.", "Feel at ease in the world and use thinking as a reflection of a desire to merge with the world."],
                "6": ["Like to remain easygoing.", "Tend to be much more trusting of others.", "This type, when stressed, looks like an unhealthy Type B—self-developing and energetic."],
                "7": ["This type tends to avoid conflict or over excitement.", "As they become unhealthier, become more passive and indifferent.", "Seeks to maintain state of contentment--not too excited nor in discomfort."],
                "8": ["Dislike contention and would rather agree to keep the peace.", "As they become unhealthier, become more passive and disengaged."],
                };

var mistypes = {"12": ["These two types are often easy to tell apart, unless someone is differentiating between wing types. Both serious, conscience-driven, of service, can be very altruistic.", "", ""],
                "13": ["Both efficient and highly organized, but..", "", "Both put feelings aside for the sake of efficiency, becoming cool and impersonal but…", "", ""],
                "14": ["These two types are often easy to tell apart. They might seem similar if focusing mostly on the negative aspects: perfectionistic, dissatisfied, frustrated, perceived as fussy or picky.", "Both critical and picky, but…", "", "Both are related because…"],
                "15": ["Can both be considered deep thinking types, but…", "", ""],
                "16": ["These two types are often easy to tell apart.", "Both are compliant types (“should” or “must”), but…", "", "Both may feel guilty, but…"],
                "17": ["Both are related because…", "Both share idealism and a sense of “mission,” holding high ideals, but…", "", "Both might express “perfectionism”, but…", "Still, there exist a number of differences."],
                "18": ["Both have strong wills and action-oriented, but…", "Both are involved with justice, but…", "Both may have aggressive impulses, but…"],
                "19": ["These two types may be confusing if someone is differentiating between wing types. This could be difficult. Both can be idealistic, philosophical, and somewhat withdrawn, but…", "", ""],
                "23": ["These two types may be confusing if someone is differentiating between wing types. Both lean into the desire to be liked and please others, but…", "", "", "Both may seem ambitious, but…"],
                "24": ["Both are feeling, sensitive types. Both (and really, all types) can be depressed. They put great emphasis on the ups and downs of relationships, but…", "", ""],
                "25": ["These two types are very easy to tell apart. Both may feel rejected easily, but…", "", ""],
                "26": ["Both are warm and engaging, wanting to be liked, but…", "Both ingratiate themselves with people, but…", "Both types are emotional, but…", "", ""],
                "27": ["Both can be emotional and histrionic, but…", "Both are gregarious and enjoy being with people, but…", "", "", "", ""],
                "28": ["Both may dominate others, but…", "", "Both struggle with rejection, but…", "Both are related because…"],
                "29": ["Both are interpersonal, both tend to put others’ needs before their own, both believe in service, but...", "", "", ""],
                "34": ["These two types may be confusing if someone is differentiating between wing types. But…", ""],
                "35": ["Both may be intelligent thinkers, but...", "", "", ""],
                "36": ["Both can be focused on work and performance, but...", ""],
                "37": ["Both are aggressive or assertive types, both are interested in enjoying different aspects of success, but...", "Both can be trendsetters, but...", "", "Both may seem narcissistic and grandiose, but...", ""],
                "38": ["Both are ambitious and competitive, but...", "", "", ""],
                "39": ["Both are related because…", "Both are highly adaptable and interested in gaining acceptance from others, but...", "", ""],
                "45": ["These two types may be confusing if someone is differentiating between wing types. Both are withdrawn types, but…", ""],
                "46": ["Both may identify with negative emotions, but...", "", "", ""],
                "47": ["These two types are very easy to tell apart. Both may tend to be excessive, but...", ""],
                "48": ["These two types are fairly easy to tell apart. Both may encounter passionate and intense feelings, but...", ""],
                "49": ["Both may be creative, but...", "", "Both maybe withdrawn, but...", "", ""],
                "56": ["Both are thinking types, but...", ""],
                "57": ["These two types are easy to tell apart. Both are very curious and exploratory, but...", "", "", "Both are related because…"],
                "58": ["Both see themselves as outsiders and easily feel rejected, both are highly independent, both believe in direct communication, but...", "Both are related because…"],
                "59": ["Both may be intelligent, but...", "", "", "", "Both may ask “What if?” questions, but...", "", ""],
                "67": ["These two types may be confusing if someone is differentiating between wing types. Both are thinking types, driven by anxiety, but…", ""],
                "68": ["Both may be aggressive, but...", ""],
                "69": ["Both concerned with security and maintaining the status quo, both tend to take modest views of themselves, but...", "", "Both are related because…"],
                "78": ["Both types are aggressive, but...", ""],
                "79": ["These two types are relatively easy to tell apart. Both can be rather busy and happy, but...", "", ""],
                "89": ["These two types may be confusing if someone is differentiating between wing types.", ""],
                }

var list_mistypes = [mistype1, mistype2, mistype3, mistype4, mistype5, mistype6, mistype7, mistype8, mistype9];